### ISSUE TITLE
2FA authentication not handled 

### ISSUE THREAD

**Issue by jeson114** [steveukx/git-js#203]

**Comment by steveukx** [comment]
To look into this - do you have an example of using 2FA with the standard git binary?

**Comment by jeson114** [comment]
I guess this should be handled only with SSH

**Comment by chris-dura** [comment]
So, [nodegit](http://www.nodegit.org/guides/cloning/ssh-with-agent/) has some guides on logging in using "SSH with an Agent", but simple-git is much easier for me to understand as far as cloning etc. I'm a novice when it comes to authentication, and I can't tell what I would have to do to use SSH with simple-git (instead of providing username/password in URL), or if it's even possible?

**Comment by steveukx** [comment]
Assuming that you're connecting to github - based on the detail in https://github.com/blog/1614-two-factor-authentication, if you are using 2FA set through an SSH connection (ie you've cloned with ssh, for example `git@github.com:steveukx/git-js.git`) then you need do nothing more than set up the necessary SSH keys for the user you're running the `simple-git` process as.

If you're using an HTTPS connection (eg `https://github.com/steveukx/git-js.git`) then you should use an [access token](https://github.com/settings/tokens) in place of your usual username and password. The access token can then be used in place of the password in the [URL used to clone](https://github.com/steveukx/git-js#authentication).

If you're using HTTPS and always use the same account to connect to github, you can omit the credentials from the clone URL and instead use a [.netrc file](https://gist.github.com/cactus/3925422) on the machine to use default credentials for basic authentication (also [see here](https://gist.github.com/technoweenie/1072829)).

**Comment by jeson114** [comment]
yea . worked for me
