### ISSUE TITLE
why use simpleGit.diff in the server can't console the status?

### ISSUE THREAD

**Issue by smbera** [steveukx/git-js#232]
simpleGit.diff(function(err,status){
	    console.log(status); 
}
//it console empty

**Comment by steveukx** [comment]
To provide better help, please include the version of the library you are using along with the output you would see if you run `git diff` from the terminal.

There are a couple of reasons for `status` being empty - when there are no changes and when there was an error running the command (in which case `err` would have a value).

You can use `simpleGit.diffSummary(function (err, status) { ... })` which returns a [DiffSummary](https://github.com/steveukx/git-js/blob/master/src/responses/DiffSummary.js) rather than returning the raw string data as you would get in the `.diff` command.

**Comment by steveukx** [comment]
Closing due to no reply.
