### ISSUE TITLE
Typing and Documentaion

### ISSUE THREAD

**Issue by OiYouYeahYou** [steveukx/git-js#268]
I've just had a quick audit what methods on SimpleGit are documented and have type definitions. And am wondering if you would accept a PR to improve? And if so, are there any considerations I should make?

Here is a list of work that needs to be done, as well as the current state of documentation

#### Untyped but Documented
* [x] .checkIgnore
* [x] .checkoutLatestTag
* [x] .clean
* [x] .clearQueue
* [x] .commit
* [x] .customBinary
* [x] .cwd
* [x] .deleteLocalBranch
* [x] .env
* [x] .exec
* [x] .getRemotes
* [x] .init
* [x] .listRemote
* [x] .mirror
* [x] .mv
* [x] .outputHandler
* [x] .pushTags
* [x] .raw
* [x] .rebase
* [x] .removeRemote
* [x] .reset
* [x] .revert
* [x] .rm
* [x] .rmKeepLocal
* [x] .show
* [x] .stash
* [x] .tag

#### Untyped and Undocumeted
* .binaryCatFile
	* [ ] Documentation
	* [ ] Typing
* .remote
	* [ ] Documentation
	* [ ] Typing
* .stashList
	* [ ] Documentation
	* [ ] Typing
* .subModule
	* [ ] Documentation
	* [ ] Typing
* .submoduleAdd
	* [ ] Documentation
	* [ ] Typing
* .submoduleInit
	* [ ] Documentation
	* [ ] Typing
* .submoduleUpdate
	* [ ] Documentation
	* [ ] Typing
* .then
	* [ ] Documentation
	* [ ] Typing
* .updateServerInfo
	* [ ] Documentation
	* [ ] Typing
* .updateServerInfo
	* [ ] Documentation
	* [ ] Typing

#### Typed and Documented
* .add
* .addAnnotatedTag
* .addConfig
* .addRemote
* .addTag
* .branch
* .branchLocal
* .catFile
* .checkIsRepo
* .checkout
* .checkoutBranch
* .checkoutLocalBranch
* .clone
* .diff
* .diffSummary
* .fetch
* .log
* .merge
* .mergeFromTo
* .pull
* .push
* .revparse
* .silent
* .status
* .tags

#### Privates
* ._catFile
* ._command
* ._env
* ._getLog
* ._outputHandler
* ._parseCheckIgnore
* ._parseCheckout
* ._rm
* ._run
* ._schedule
* ._silentLogging

**Comment by steveukx** [comment]
Hi, I would happily accept a new PR either to update the typings or switch the repo over to using TypeScript as its source language. Unfortunately I don't really have the time to maintain it fully at the moment.

When you open a PR, Travis will automatically run the existing unit tests against your changes, so long as they are still passing, I can usually merge and release within a day or so.

**Comment by NomisIV** [comment]
I don't know if this is considered necro bumping, but since the issue is still open, I figured it would be better to ask it here than to open a new issue.

I'm having problems with the typings for `.add()` and `.stash()` (there are probably more functions with the same issue as these). The API Documentation on the npm page and the source agree on both functions having a second parameter (a callback function), whilst the typing doesn't include the parameter. I also suspect there is something fishy with their return type, since TypeScript is giving me errors while the JavaScript runs just fine.

[src/git.js:249](https://github.com/steveukx/git-js/blob/27c3f1bceffad11ac73d2f6a10279033cda02acf/src/git.js#L249)
[typings/simple-git.d.ts:20](https://github.com/steveukx/git-js/blob/27c3f1bceffad11ac73d2f6a10279033cda02acf/typings/simple-git.d.ts#L20)

**Comment by steveukx** [comment]
Hi, no problem for resurrecting an old issue.
The typescript definitions were originally created to work when importing (the now deprecated) `simple-git/promise`, and as such there was no callback argument. Now that the main `simple-git` import supports callbacks as well as async and promises, I've added the callback argument into the definitions.
