### ISSUE TITLE
checkoutBranch error ("File name to long")

### ISSUE THREAD

**Issue by divramod** [steveukx/git-js#291]
Hey, 

i tried to checkout a new branch with git raw which is running fine

```
    const TEST_DIR = path.resolve('/tmp/test/test')
    const R_GIT_INIT = await git(TEST_DIR).init()
    const R_GIT_CHECKOUT = await git(TEST_DIR).
        'checkout',
        '-b',
        'test123'
    ])
```

but when using checkoutBranch, for which i expect the same result, i got an error message

```
    const TEST_DIR = path.resolve('/tmp/test/test')
    const R_GIT_INIT = await git(TEST_DIR).init()
    const R_GIT_CHECKOUT = await git().checkoutBranch('test123')
```

the error message

```
fatal: failed to stat 'function (err, result) {
               if (err) {
                  reject(new Error(err));
               }
               else {
                  resolve(result);
               }
            }': File name too long

```

Any hints on that?

**Comment by ontoneio** [comment]
@divramod I understand this issue is over a year old now, but did you have any success in figuring out what the issue was?

I have ran into this same issue with the same error message.

Any hints would be much appreciated.

**Comment by divramod** [comment]
hey @ontoneio, i moved on with that, sorry. i think, in the end i used shelljs or the raw function to solve my problem.

**Comment by steveukx** [comment]
Apologies it's a _very_ late reply, but this is likely because the function is being called with only one argument, especially if the `simple-git` was imported as the (now deprecated) `simple-git/promise`.

`checkoutBranch` takes two arguments, the `branchName` and a reference `startPoint`. As the `startPoint` was missing from, it would likely have been filled in with a function, which would have been coerced to a string before being passed to the underlying `git` process, and would be too long as a branch name,

The correct usage would have been `await git().checkoutBranch('test123', 'origin/main')`.

If ever you see unexpected errors, you can find likely causes by enabling full debug logging https://github.com/steveukx/git-js#enable-verbose-logging.
