### ISSUE TITLE
Not really clear how to use options

### ISSUE THREAD

**Issue by ScreamZ** [steveukx/git-js#294]
Hello, I'm having difficulties to pass options to commands…

```js
const tags = await git.tags({ "--list": 'v*.*.*' })
```
Is not working `error: option `list' takes no value`

Even if I try
```js
const tags = await git.tags("--list 'v*.*.*'")
const tags = await git.tags("v*.*.*")
const tags = await git.tags(['v*.*.*'])
```

The command run but the pattern is not matching, it does if I manually run the command `git tag --list 'v*.*.*'`

Can you detail the syntax please ?

Also having issues with:

```js
git.stash(['push', {"--message": "My Message"}])
```

Which is not working…

Best regards

**Comment by lghamie** [comment]
Could you filter the tags?

**Comment by ScreamZ** [comment]
what ?

**Comment by velkovb-nuk** [comment]
I have the same issue, cannot specify value for --list.

**Comment by steveukx** [comment]
Options are supported by most functions in the `simple-git` api, and where supported can be supplied either as a trailing array of strings or object literal - the structure of which is documented in https://github.com/steveukx/git-js#how-to-specify-options

Since this was opened back in 2018 there is now much wider support for options, including the `.tags()` end point. As `.tags()` implies the use of `--list` already, you need just pass the tag filter string, for example assuming a repo has tags created with the names `v1.0`, `v1.1`, `v2.0` and `v2.1`:

```javascript
const simpleGit = require('simple-git');

async function app () {
    const git = simpleGit();

    console.log(await git.tags(['v1.*']));
    console.log(await git.tags(['--list', 'v1.0']));
    console.log(await git.tags({'v2.*': null}));

    // this would fail because it would result in an argument of --list=v2.0 being passed to
    // the git binary, but --list is positional only and therefore must not be given a value
    // console.log(await git.tags({'--list': 'v2.0'}));
}


app();
```

If you don't need the tag list parsing functionality added by the `git.tags()` method, you can use `git.tag()` which would take the form:

```
git.tag(['--list', 'v1.*', ...anyOtherSortingOptionsEtc ])
```
