### ISSUE TITLE
Ignores basedir if current folder already has a .git folder

### ISSUE THREAD

**Issue by r0bnet** [steveukx/git-js#295]
Hey!

I really found a very strange behaviour. v 1.97.0

Imagine this is my folder structure:

-  /a
- /a/.git
- /a/index.js
- /a/repo

I'm executing index.js in /a. `repo` dir is completely empty. My code:

```js
const path = require('path');
const git = require('simple-git/promise');

const myGit = git(path.join(__dirname, 'repo'));
myGit.checkIsRepo()
  .then(isRepo => console.log(isRepo));
```

This prints `true` but it should not, because `repo` is completely empty. If i rename the `.git` folder to e.g. `_.git` then it works (is now working inside `repo` instead of inside `a`).

Same is true for some other commands (i tested with `.raw()`). 

It seems as if simple-git ignores what the baseDir argument is when the current working dir is a git repository.

**Comment by thirdender** [comment]
> .checkIsRepo(handlerFn) | Determines whether the current working directory is part of a git repository, the handler will be called with standard error object and a boolean response.

Because `/a` is a git repo, and `/a/repo` is "part of" (a subdirectory of) `/a`, `checkisRepo()` is returning the correct value.

Or, think of it another way. If you had a folder `/repo` that contained your git repository, and you had a subdirectory under that `/repo/src`, that subdirectory would be considered "part of" the git repository.

The git CLI tool works this way as well. In the example above, you could do `cd /repo/src ; git pull` and git would find the `/repo/.git` directory even though you weren't in `/repo` at the time.

You could probably get what you originally wanted by doing a simple check for the file `/a/repo/.git/config`, but I'm not sure if this is a complete check that works in all situations.

**Comment by r0bnet** [comment]
You're right, i've completely overseen that. Shame on me. But thanks for your answer!

I think i'll try something different. I'll work with the `.raw(...)` method and then use this:

```bash
git rev-parse --show-toplevel
```
and compare the answer with the directory where it is executed.

**Comment by dperrymorrow** [comment]
what brought me here was trying to init simpleGit with the root dir of the repo rather than my current dir. _This was causing problems for pathing of files in git_ 

the following works nicely, thanks for the above example. 
```javascript
const simpleGit = require("simple-git/promise");
const path = require("path");

module.exports = {
  async init() {
    const tempGit = simpleGit();
    const res = await tempGit.raw(["rev-parse", "--show-toplevel"]);
    const root = path.normalize(res.trim());
    return simpleGit(root);
  },
};
```
