### ISSUE TITLE
"(HEAD -> master)" is part of most recent commit message in `log`

### ISSUE THREAD

**Issue by garyking** [steveukx/git-js#297]
When I run `log` to get commits on a repo, `(HEAD -> master)` is part of the `message` for the most recent commit. I know this appears in `git log`, but shouldn't this package remove this text for us? Or should I just remove it myself? 

Or is there even a git config to remove this text, if necessary?

**Comment by njpanderson** [comment]
+1 on this, would be interested to know.

**Comment by RobertAKARobin** [comment]
This is bothering me too.

**Comment by Seb35** [comment]
This was bothering me too, then I use the argument `{ format }` for a specific format – `{ hash: '%H', message: '%s' }` in my case, I don’t need more.

The default `'%s%d'` is a bit strange because it mixes data of different types: the message, a very part of the commit, and the branches, which are local to the repo and could easily change. I propose to remove the `'%d'` from the key `'message'` and add another key `'branches'`.
