### ISSUE TITLE
simple-git is unreliable

### ISSUE THREAD

**Issue by fabiospampinato** [steveukx/git-js#320]
Different runs of its functions sometimes return different results, I can't use this in my projects if it's unreliable.

https://github.com/steveukx/git-js/issues/317
https://github.com/steveukx/git-js/issues/302
https://github.com/steveukx/git-js/issues/297

Can this project be made more reliable?

**Comment by steveukx** [comment]
Hi. It's a valid concern - the problem is to do with the inconsistent order of close/exit events in the underlying spawned `child_process` instances ([this commit](https://github.com/steveukx/git-js/commit/777ecfaa9a20ff5d843c43caf3242901497a6c3f#commitcomment-27900143) has some interesting commentary).

This will mostly only appear now if you run many commands in parallel, so using a library like [async](https://caolan.github.io/async/docs.html#parallelLimit) to throttle the number of spawned processes, or just [running your commands in series](https://github.com/steveukx/git-js/issues/317#issuecomment-428549633) would mean you no longer get this error.

In the v2 milestone release it will be easier to configure the spawning of child processes, so this should be resolved for good soon. In the mean time, please feel free to create failing test cases such as [test-concurrent-commands](https://github.com/steveukx/git-js/blob/master/test/integration/test-concurrent-commands.js) that match your use case so I have some acceptance criteria to go with.

**Comment by fabiospampinato** [comment]
> In the mean time, please feel free to create failing test cases

Unfortunately I'm unable to produce these problems reliably.

**Comment by steveukx** [comment]
In that case, it's most likely down to spawning too many child processes concurrently. I'd recommend checking out the [async.parallelLimit](https://caolan.github.io/async/docs.html#parallelLimit) helper to ensure you don't overload the system. Watch the [v2](https://github.com/steveukx/git-js/milestone/2) milestone for updates on how the rewrite is going.

**Comment by edbrannin** [comment]
Do you expect too-many-child-processes be the cause when running several parallel `simple-git/promises` instances in different repositories (which is what I'm seeing), or just when it's in the same repo?

Also, for anyone else who comes here after me, [async.parallelLimit's docs appear to have moved](https://caolan.github.io/async/v3/parallelLimit.js.html).

**Comment by rxliuli** [comment]
2021 is coming, is there any progress?
