### ISSUE TITLE
feat: `git rev-list` is missing

### ISSUE THREAD

**Issue by Val-istar-Guo** [steveukx/git-js#329]
**reason**
I want to use command `git rev-list --left-only --count origin/master...test/branch` to get how many commit does test/branch behind the origin master. 

**expect**
add `rev-list`?

**additional**
I don't know if there are other way that can achieve the same function.(except `childProcess.exec`)

**Comment by steveukx** [comment]
Hi, for any feature of the `git` api that isn't covered by a bespoke method, you can use `git.raw(...)`, detail of which is in the readme: https://github.com/steveukx/git-js#complex-requests

If you would like to create a pull request, please do - otherwise if you include the full response this command generates I can have a parser added when I have more time at the start of next year.
