### ISSUE TITLE
Need to get result from push api

### ISSUE THREAD

**Issue by cwtuan** [steveukx/git-js#330]
Is possible to get result of `push` such as commit id?

**Comment by steveukx** [comment]
The detail of the push itself is currently not parsed at all and the full content of stdout is returned to your handler. The response to a push doesn't generally include commit IDs as those are created when committing either explicitly or implicitly (ie: merge commits as part of a pull). Can you include the full git command you would use on the command line and the response it generates?

Examples of how parsers are added can be found in [fetch](https://github.com/steveukx/git-js/blob/master/src/git.js#L373) and the associated [parser](https://github.com/steveukx/git-js/blob/master/src/responses/FetchSummary.js). If you would like to make a pull request, please do - otherwise I've tagged this as an enhancement to be added when I have more time at the start of next year.

**Comment by cwtuan** [comment]
Currently, I retrieve the last commit record from the commit log in that branch after git push.

**Comment by faizanvahevaria** [comment]
Hi,
Please help me to use push command using this package. 
I am using the following code using thie package 

git(_mdirname)
          .push(['-u', 'origin', 'master'], () => console.log('done'));

I am not getting any error and not able to push my commits to remote.

**Comment by mizi-lin** [comment]
2 years have passed，a u ok?

**Comment by steveukx** [comment]
Hi, apologies for having missed off the resolution - `git.push` responds with a `PushResult` see https://github.com/steveukx/git-js/blob/91d6bfdb8c115c2511b55c0bccb3854d0e7775e7/typings/response.d.ts#L423
