### ISSUE TITLE
Not being able to return array of the log

### ISSUE THREAD

**Issue by danielsimao** [steveukx/git-js#337]
Hi,

I'm trying to use the log command to run some statistics but i'm only able to console.log the result. If I try to return the value from the log command, it simply returns a Git object. Can someone help to get this log value?

`
getLogs = path => {
  return git(path).log((err, log) => log);
};
`

**Comment by Dar0n** [comment]
Hey @danielsimao I'm in the same boat with you.
Still don't completely understand how it works, but this thing works with Promises, therefore you have to handle returned value inside the function.

1. Like in the example:
```
require('simple-git')()
    .log((err, log) => {
    const result = log
    // do something with the result
})
```
2. Use promise version
```
const git = require('simple-git/promise')()
git.log().then(data => {
  const result = data
  console.log(result.all[0])
  // again do something with the result
})
})
```
3. Using async functions (which is essentially option 2 with syntactic sugar)
```
const git = require('simple-git/promise')()
const gitLog = async function () {
  return git.log()
}
const myMethod = async function () {
  const data = await gitLog()
  console.log(data.all[0])
  // once again you do something with the data
}
myMethod()
```
To make it (hopefully) a bit more clearer, you could declare a variable beforehand and then inside the Promise callback assign this variable to the returned object:
```
const git = require('simple-git/promise')()
let result = 'not initialized'
const gitLog = async function () {
  result = await git.log()
}
gitLog()
setTimeout(() => console.log(result), 2000)
```
But as it is an asynchronous code,  it takes time to execute, and you can see that the value has changes e.g. after timeout. But since it is not clear how long should be the timeout, the proper way to do what you want is to handle everything inside the callback. That way you make sure that the value is awaited and only then assigned to your variable.

I hope this somewhat makes sense. :) Perhaps, later on someone could give a better explanation.

**Comment by danielsimao** [comment]
@Dar0n, thank you for the reply. The best way I found to work around the issue is to use Promises.
