### ISSUE TITLE
The renamed file is not properly saved in the StatusSummary

### ISSUE THREAD

**Issue by Symbolk** [steveukx/git-js#399]
Related with #105 , I find that renamed files do not correctly appear in the *renamed: []* array of the StatusSummary, but they do appear in the *files: []* array.

Run `git status` under a git repo with one renamed file:
![image](https://user-images.githubusercontent.com/14107297/66394299-5f891200-ea07-11e9-97e1-ceed68bd1b8f.png)

Run git-js under the git repo:
```javascript
var git = require('simple-git')

git = git('f:/workspace/dev/SmartCommitCore')
git.status((err, res) => {
  if (err) {
    console.log(err)
  }
  console.log(res)
})
```
It outputs:
![image](https://user-images.githubusercontent.com/14107297/66394398-97905500-ea07-11e9-979b-42da48a43e3d.png)

**Comment by steveukx** [comment]
Hi, apologies for the delay in getting back to you - did you find a reason to this?

If you find this issue again, please run `git status --porcelain -b -u` to show the actual output this library parses in order to build the status summary object.

I have added another test in [test-status.js](https://github.com/steveukx/git-js/blob/master/test/unit/test-status.js#L27-L41) that shows a renamed file is picked up as a rename when `git status --porcelain -b -u` denotes the modification with an `R`.
