### ISSUE TITLE
addRemote or remote passing options does not working on a cloned repo

### ISSUE THREAD

**Issue by RaphaelGuimaraes** [steveukx/git-js#452]
Hello everyone!

What I'm trying to do is to clone a repository with a boilerplate that I have and after this change the remote origin for any new repository that I want.

When I try to do by **git.remote([options])**, I don't receive any error, but when I check the **remote origin** isn't the origin that I want. Example:

`git.remote([
	"set-url",
	"origin",
	"https://my-new-repository",
])
.then((res) => spinner.succeed("Remote origin associated"))
.catch((err) => console.log(err));`

And when I try to do by **git.addRemote** like this:

```
git.addRemote("origin","https://my-new-repository")
.then((res) => spinner.succeed("Remote origin associated"))
.catch((err) => spinner.fail("Remote origin already exists"));
```

I fall on **catch** returning **"Remote origin already exists"**.

Am I implementing wrong or any idea why its not working?

Thanks.

**Comment by steveukx** [comment]
At the moment, neither the `addRemote` or `remote(['set-url', ... ])` commands will return any data on success (given that none is sent back from the `git` binary for those commands).

I've added an [integration test](https://github.com/steveukx/git-js/blob/master/test/integration/test-remote.js#L27-L45) that uses so you can see how this is done (albeit with async/await rather than promises):

Starting from a fresh repo (after a `git init`), I add the `origin` remote and use `getRemotes(true) to assert the remote was added [source](https://github.com/steveukx/git-js/blob/master/test/integration/test-remote.js#L35-L38)

```
await git.addRemote(repoName, initialRemoteRepo);
expect(await git.getRemotes(true)).toEqual([
  {name: repoName, refs: {fetch: initialRemoteRepo, push: initialRemoteRepo}},
]);
```

Then set the remote's url to something new, and again use getRemotes(true) to assert the change was made: [source](https://github.com/steveukx/git-js/blob/master/test/integration/test-remote.js#L40-L43)

```
await git.remote(['set-url', repoName, updatedRemoteRepo]);
expect(await git.getRemotes(true)).toEqual([
  {name: repoName, refs: {fetch: updatedRemoteRepo, push: updatedRemoteRepo}},
]);
```

To look into this further for you, please let me know which version of node / simple-git you're using, whether you are unix or windows and please share how you `require` in the library and create the `git` instance. Thanks

**Comment by RaphaelGuimaraes** [comment]
Hi, the truth is that I had to change the cwd before this commands. When I did `git.cwd(dir);`, I got the result that I want. Thanks for the help..
