### ISSUE TITLE
gitRemotes: Breaking change introduced with v2.5.0

### ISSUE THREAD

**Issue by medikoo** [steveukx/git-js#512]
We've upgraded from v1 to v2 following changelog notes: https://github.com/steveukx/git-js/blob/master/CHANGELOG.md#200---incremental-switch-to-typescript-and-rewritten-task-execution

As we didn't use any methods starting with `_`, we assumed it's safe to upgrade. Yet our apps started to crash due to change in format of values as returned by `gitRemotes()`:

v1

```javascript
 console.log(await git.getRemotes()); // [ { name: 'origin', refs: {} } ]
```

v2

```javascript
 console.log(await git.getRemotes()); // [ { name: 'origin' } ]
```

As I additionally tested, this behavior changed between v2.4.0 and v2.5.0. So technically it's a breaking change introduced with v2.5.0

**Comment by steveukx** [comment]
Hi, thank you for pointing this out.

In many cases the upgrade from 1.x to 2.x will be seamless, but clearly not in all cases. As part of the major version change, much of the documentation for types was updated to match the returned data format, but in cases where the documentation better represented the data than the actual data, the returned format was changed to match the documentation.

In this case `getRemotes()` and `getRemotes(false)` have always been documented as just returning `RemoteWithoutRefs[]` which is why you are seeing the returned data in the format `[ { name: "" } ]`.

If you want to include the ref detail, please use `getRemotes(true)` which will populate the ref detail.

I have left a comment for you in the related pull request - in versions of `simple-git` prior to `2.5.0` you would be able to reference `refs.fetch` but it would always be undefined. In versions `2.5.0` onwards, if you need to access the refs, you must opt in to fetching them by using `getRemotes(true)`.

I will add a note to the upgrade readme for our next release. If you have any other queries on your upgrade of simple-git from 1.x to 2.x please do reach out again.

**Comment by medikoo** [comment]
Thanks @steveukx for clarifications, indeed we missed _verbose_ flag. So anyway we didn't resolve remotes as expected.

Technically removing `refs` could be considered as design bug fix, assuming it's destined to be empty with no _verbose_ flag.

**Comment by steveukx** [comment]
Removing the empty refs object was indeed a bugfix in the v2 upgrade.

V1 would work as follows:

```
expect(await git.getRemotes()).toEqual([ { name: 'origin', refs: {} } ]);
expect(await git.getRemotes(false)).toEqual([ { name: 'origin', refs: {} } ]);
expect(await git.getRemotes(true)).toEqual([ { name: 'origin', refs: { fetch: '...', push: '...' } } ]);
```

Where the documentation only referred to `refs` being there when you had explicitly requested them.

In V2 you will get:

```
expect(await git.getRemotes()).toEqual([ { name: 'origin' } ]);
expect(await git.getRemotes(false)).toEqual([ { name: 'origin' } ]);
expect(await git.getRemotes(true)).toEqual([ { name: 'origin', refs: { fetch: '...', push: '...' } } ]);
```
