### ISSUE TITLE
commit error on node 10

### ISSUE THREAD

**Issue by shiftonetothree** [steveukx/git-js#544]
message.flatMap on node 10,when upgrade to node 14,problem solved.

**Comment by steveukx** [comment]
Hi, thanks for opening the issue... I've added a [note to the readme](https://github.com/steveukx/git-js#legacy-node-versions) and a [worked example](https://github.com/steveukx/git-js/blob/main/docs/LEGACY_NODE_VERSIONS.md) with details of the polyfills required in order to use `simple-git` with node.js versions 10 and below.
