### ISSUE TITLE
Inconsistent results from methods

### ISSUE THREAD

**Issue by prevuelta** [steveukx/git-js#557]
When running `git.log` or `git.remote` results vary (git 1.8.x) eg.

```
const logs = await git.log({ file });
```
returns 
```
  hash: 'd4a703f32ab09f15836d4e2fcde57a5ae3ac7b68',
  date: '%aI',
  message: 'init',
  refs: '%D',
  body: '',
  author_name: 'REDACTED',
  author_email: 'REDACTED
```

But will return `null` intermittently??

`git.remote` will return correct data sometimes and an empty array other times?

Script is:

```
const simpleGit = require('simple-git');
const path = require('path');
const glob = require('glob');

const cwd = process.cwd();

const git = simpleGit({ baseDir: cwd, maxConcurrentProcesses: 6 });

const files = glob.sync(path.join(__dirname, '/docs/**/*.md'));

console.log(files);

files.forEach(async file => {

const isRepo = await git.checkIsRepo();

 console.log("Isrepo", isRepo);

 const log = await git.log({ file });

console.log("File", file);

 console.log("Log entry", log.latest);
  const remotes = await git.getRemotes(true);
console.log("Remotes", remotes);
});

```

**Comment by prevuelta** [comment]
Will run with DEBUG vars and see what it says...

**Comment by prevuelta** [comment]
Looks like it gets the stdOut after it's processed? (log10)

![image](https://user-images.githubusercontent.com/4637801/102725620-f7f58300-437c-11eb-829a-aef3c6c6a525.png)

**Comment by steveukx** [comment]
Hi, in order to look into this for you, please can you paste the complete log (or at least the complete log for the command that is unexpectedly returning null, which appears to be `DEBUG=simple-git,simple-git:*:10).

Based on the code sample you have included, it is possible that the glob returns files not tracked by git - the `git` instance uses the repo in the current working directory however the files glob is based on the directory containing the script you are running, if `process.cwd() !== __dirname` the results could be unexpected.

You have increased the number of `maxConcurrentProcesses` - try reducing this to 1 or 2 which helps ensure the timeliness of events in the spawned `child_process`es

**Comment by prevuelta** [comment]
Thanks, will try the maxConcurrentProcesses. I don't think it's untracked files as it sometimes returns the correct result for a single file and sometimes null.

**Comment by prevuelta** [comment]
I will try and reduce to a single example although I think it only happens when there are a few concurrent things happening
