### ISSUE TITLE
Clone particular branch

### ISSUE THREAD

**Issue by richardrich991** [steveukx/git-js#599]
Hi Team, 

I am facing an issue 

we have options for select branch while clone but I am not able to clone the branch which I am mentioning, It always cloning the default branch.

eg: git.clone("gitlab.com/basemanager", "temp", {"--branch": "mybranch" });

**Comment by steveukx** [comment]
Hi, you are using the api correctly - your call would be translated into:

```
git clone --branch=mybranch gitlab.com/basemanager temp
```

Please try running the command directly from terminal to check you are able to clone the branch you have specified.

In order to look into this any further for you, please enable [verbose debug logging](https://github.com/steveukx/git-js/tree/main#enable-verbose-logging) (or at minimum `DEBUG=simple-git:task:clone:*,simple-git:output:clone:*`) and include this output in the issue report.

**Comment by richardrich991** [comment]
Thanks, @steveukx,  it helped me a lot.

Regards,
Richard B
