### ISSUE TITLE
.cwd() does not respect multiple chains

### ISSUE THREAD

**Issue by barretron** [steveukx/git-js#614]
It looks like, when `.cwd()` is called in multiple chains, it overrides the working directory in in all other chains.

For example, in the following code sample:

```js
const { default: simpleGit } = require('simpleGit');

const git = simpleGit();

async function status(dir) {
  return git.cwd(dir).status();
}

Promise.all(['/clone/1', '/clone/2', '/clone/3'].map(status))
  .then(console.log)
  .catch(console.error);
```

I expect the `StatusSummary` for each working directory to be output:

```js
// Note: output simplified for clarity
[StatusSummary<'/clone/1'>, StatusSummary<'/clone/2'>, StatusSummary<'/clone/3'>]
```

But, instead, the `StatusSummary` for the last path is repeated 3 times:

```js
[StatusSummary<'/clone/3'>,StatusSummary<'/clone/3'>,StatusSummary<'/clone/3'>]
```

(In case you were wondering, I chose to attempt this with a single `SimpleGit` instance in order to put a hard cap on the number of child processes spawned at once, since the docs say that the child process limit is per-instance rather than library-wide).

**Comment by steveukx** [comment]
Hi, thanks for opening the issue.

This had initially been by design but as the library has evolved with better support for chains, it makes sense to be able to use either a chain or root level switch to the working directory.

As of version [2.39.0](https://github.com/steveukx/git-js/releases/tag/v2.39.0) You can now use `git.cwd({ path: string, root?: boolean })`  (with either `root` omitted or set to `false`) to impact only the current chain

Examples for use are in the [docs](https://github.com/steveukx/git-js/blob/main/examples/git-change-working-directory.md) or [integration tests](https://github.com/steveukx/git-js/blob/main/test/integration/change-directory.spec.ts)

**Comment by barretron** [comment]
Very cool that you could implement this while maintaining backward compatibility. Thanks so much!
