### ISSUE TITLE
[question] Access Private repo without cloning

### ISSUE THREAD

**Issue by jd-0001** [steveukx/git-js#641]
I checked the guide regarding authentication but it clones the repo. I just simply want to fetch the latest commits of my private repo.

So, is there anything I can configure to access the private repo?

**Comment by dperetti** [comment]
It's actually a git question.
I guess `git log origin/master` should work.

**Comment by jd-0001** [comment]
Thanks for the information. I am trying to fetch the latest commits of my repo and want to render it in markdown: [VueUse](https://vueuse.org/recent-updated.html)

Their code: [File](https://github.com/vueuse/vueuse/blob/main/scripts/recent-updated.ts)

I just don't know how to access private repo.

After the latest response, I was able to somehow initialize the repo but fetching is taking years (not completing):

Below is my code:

```js
const simpleGit = require('simple-git');
const git = simpleGit();

// my USER, PASS & REPO variable

const get_commits = async () => {
    const remote = `${USER}:${PASS}@${REPO}`;
    console.log('adding log')

    // adds a remote called 'private' with your credentials
    await git.init().addRemote('private', remote);

    console.log('fetching private')
    // fetch commits from that remote
    await git.fetch('private', 'main');

    console.log('getting log...')
    await git.log({ maxCount: 100 })
    console.log('got log')
}

get_commits()
```

Also, the main question is can I get commits of repo without getting local copy like we have above after `git.init()`

Regards.

**Comment by steveukx** [comment]
In order to run `git log`, you do need to have used `git fetch` to load the commit data first - as far as I'm aware (see official docs for [log](https://git-scm.com/docs/git-log) and [fetch](https://git-scm.com/docs/git-fetch)) there is no way to configure `git log` to query the remote remotely.

You can however limit the amount of detail you're fetching by using the `--depth=n` option when you fetch, for example:

```
await git.fetch('private', 'main', ['--depth=5']);
```

You may also want to consider using the [progress plugin](https://github.com/steveukx/git-js/blob/main/docs/PLUGIN-PROGRESS-EVENTS.md) to monitor the progress of the `fetch`

**Comment by jd-0001** [comment]
Thanks for the guidance. :relaxed: 

Regards.
