### ISSUE TITLE
Undocumented breaking change in git clone from version 1 to version 2

### ISSUE THREAD

**Issue by superhero** [steveukx/git-js#668]
This code worked in 1.107.0:

`await this.simpleGit.clone(repository, target, { depth:1 })`

But in version 2.44.0 it throws a git error:

```
Error: To many arguments
```

I can not see how the library composes the command to be able to debug what went wrong, but I follow up on this tread if I find the cause.

**Comment by superhero** [comment]
After looking through the code, We in out company found that if we use `await this.simpleGit.clone(repository, target, 'depth', 1)` then it will work. But that does not reflect the documentation imo.

I also don't know if this really composed the git command I expect.

**Comment by superhero** [comment]
https://github.com/steveukx/git-js#how-to-specify-options

This documentation describes the difference, it's not expected to define the prefixed hyphens: "--" before key. Perhaps this was always the case, but that this never complained before, just ignored the input error.. idk.. but problems solved imo

**Comment by steveukx** [comment]
Hi, thanks for opening the issue.

As you've suggested - supplying `{depth: 1}` would always have been an error in that `simple-git` has never transformed `depth` into `--depth` for you.

It's worth noting that `git.clone(repository, target, 'depth', 1)` isn't a valid usage and would result in the command `git clone ${repository} ${target}`. In order to supply options, please do use the supported options format of string array or object:

```
git.clone(repository, target, { '--depth': 1 });
git.clone(repository, target, [ '--depth=1' ]);
```
