### ISSUE TITLE
SSH authentication method

### ISSUE THREAD

**Issue by bharathkv90** [steveukx/git-js#710]
Hi Steve!

Is there any way we can authenticate using SSH instead of passing the credentials in the URL?

**Comment by steveukx** [comment]
Hello. `simple-git` calls out to the `git` binary, so will use any credentials you have set up for the user that the node process runs as.

To use SSH credentials, I recommend switching to an SSH remote. For example, instead of cloning `https://github.com/steveukx/git-js.git` you would clone `git@github.com:steveukx/git-js.git`. If you already have the repo cloned, you can change the remote host by running:

```
git remote set-url origin git@github.com:steveukx/git-js.git
git fetch origin
```

(assuming your remote name is `origin`).

**Comment by bharathkv90** [comment]
Thanks a lot, Steve. This will help.
