### ISSUE TITLE
Destructuring isClean() throws an error

### ISSUE THREAD

**Issue by chmac** [steveukx/git-js#739]
I tried this:

```typescript
    const {isClean} = await simpleGit(path).status();
    ...
    return isClean();
```

But I received this error:

    TypeError: Cannot read properties of undefined (reading 'files') 
        at isClean (node_modules/simple-git/cjs/index.js:2494:22)

Somehow the value of `this` doesn't work under the scenario above (that's what I find on lin 2494):

```javascript
      isClean() {
        return !this.files.length;
      }
```

Not sure if this is a bug or intended behaviour. It caught me out and I only by chance tried avoiding the destructuring.

**Comment by steveukx** [comment]
Thank you for the detailed issue.

In general, the responses to methods from `SimpleGit` are class instances, and rely on their methods being called on the instance itself rather than called without context (as is the case with destructuring).

I have however made a small change to `StatusSummary` to allow `isClean()` to be used in this way - you should now be able to use `3.2.0` on npm with destructuring.

If you have any further problems, please do open a new issue.

**Comment by chmac** [comment]
@steveukx AMAZING! Thanks a lot, I had already refactored to call it on the instance, but I really appreciate the fast response and the change.
