### ISSUE TITLE
Error: spawn git ENOENT

### ISSUE THREAD

**Issue by Luncher** [steveukx/git-js#74]
When I create a bare repository  prompted the following errors:
Error: spawn git ENOENT
     at exports._errnoException (util.js: 860: 11)
     at Process.ChildProcess._handle.onexit (internal / child_process.js: 178: 32)
     at onErrorNT (internal / child_process.js: 344: 16)
     at doNTCallback2 (node.js: 450: 9)
     at process._tickCallback (node.js: 364: 17)
     at Function.Module.runMain (module.js: 459: 11)
     at startup (node.js: 136: 18)
     at node.js: 972: 3

code:

var simpleGit = require('simple-git');

var bareDir = 'test.git';

simpleGit(bareDir).init(true, function() {
    console.log("init bare done");
});

**Comment by AlexGustafsson** [comment]
Are you using Windows by chance?

I've found that NodeJS doesn't seem to play nice when spawning processes (such as a shell running git init --bare) on Windows.

**Comment by steveukx** [comment]
I've not tested the use of `init --bare` on windows, however this error will be thrown if the directory used as the base directory doesn't exist before git functions are called on it.

As of today's release `1.27.0` if the underlying child process emits an `error` event the content will be in the standard error argument, before this release an error event in the underlying child process wouldn't be caught and the callback would treat the result as an empty successful response rather than an error.

**Comment by Luncher** [comment]
got it thank you

**Comment by steveukx** [comment]
Closing issue - if you have problems, please feel free to re-open the issue ideally with a test case.
