### ISSUE TITLE
checkIsRepo does not work when GIT output is non english or german

### ISSUE THREAD

**Issue by yeraydavidrodriguez** [steveukx/git-js#766]
Currently, if the user has GIT configured to return its messages in other language than English or German, the method `checkIsRepo` does not work properly and returns a GIT command error.

This is caused by the way SimpleGit checks if a directory contains a GIT repository:  On `checkIsRepoTask` method (check-is-repo.ts), it checks the result of the command `git rev-parse --is-inside-work-tree`. If it fails, but the error contains the expression "_Not a git repository_" or "_Kein Git-Repository_", the error is controlled and returns false. Else, it returns the error.

This last check is performed at check-is-repo.ts, line 68.

However, when GIT is configured to use other language, the error may be, i.e. "._git non è un repository Git (né lo è alcuna delle directory genitrici)_" (Italian) or "_fatal: no es un repositorio git (ni ninguno de los directorios superiores): .git_" (Spanish), and therefore instead of false, the method will return the GIT error.

Another method, language-independent, should be used to guarantee the method executes reliably.

**Comment by steveukx** [comment]
Hello, apologies for the delay in responding to this.

Where some of the `simple-git` commands are able to handle child process exit codes to detect the result, or pass the `git` stdout straight through to the calling application, where parsers are used I now recommend configuring `simple-git` to request `git` respond in English rather than the environment's default locale.

https://github.com/steveukx/git-js/blob/main/docs/NON_ENGLISH_LOCALE.md
