### ISSUE TITLE
AWS Lambda spawn git ENOENT (with GIT_SSH_COMMAND)

### ISSUE THREAD

**Issue by ovx** [steveukx/git-js#774]
Hi,
I'm running simple-git on AWS Lambda with a GIT layer (https://github.com/lambci/git-lambda-layer) and everything works fine until I use `.env('GIT_SSH_COMMAND', 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ...')` with a custom SSH key - it throws `spawn git ENOENT`.

Works perfectly fine with the SSH key on the localhost, error happens only on lambda and only with the GIT_SSH_COMMAND env.

Any ideas why is this happening? 

- Node 14 (Lambda)
- GIT 2.29.0 (via lambda layer)
- Lambda layer is installed properly, it works without GIT_SSH_COMMAND

**Comment by steveukx** [comment]
When you use `git.env()` you will are required to set all environment variables explicitly, so it is possible that you're omitting others that are necessary to run your script.

In https://github.com/steveukx/git-js/issues/457#issuecomment-660238169 there was a recommendation to use the AWS `env` function rather than using `git.env`.

You can also try passing a full env object to git with this value overridden:

```
git.env({
  ...process.env,
 GIT_SSH_COMMAND: 'ssh ...',
});
```

Please do comment back on this issue if either of these worked and I'll have the docs updated accordingly.
