### ISSUE TITLE
fatal: reference is not a tree: <SHA>

### ISSUE THREAD

**Issue by gtk2k** [steveukx/git-js#792]
```
await fs.access(clonePath).catch(_ => {
    console.log(`clone ${clonePath}`);
    return simpleGit().clone(currentJob.cloneUrl, clonePath, ['--depth', '10', '--branch', branchName]);
});
await simpleGit(clonePath).cwd({path:clonePath}).checkout(currentJob.pushId);
```
Specifically, when I try to checkout with commit SHA after receiving a WebHook, I get an error.

The first time you do not get an error, but the second time you run it you get the error `fatal: reference is not a tree: <SHA>`.
How can I fix this problem?

**Comment by steveukx** [comment]
From the [change directory example](https://github.com/steveukx/git-js/blob/main/examples/git-change-working-directory.md), you may need to use `root: true` in the object passed to `cwd`: `.cwd({ path, root })`.

To be sure where the issue is arising though, please use the [debugging guide](https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md) to enable verbose logging and include the log in this issue.

**Comment by steveukx** [comment]
A quick google looks like it's probably not to do with changing the working directory, but instead that the `currentJob.pushId` isn't a known commit. 

When you first run this function you are cloning the repo so will have access to all commits. Subsequent runs of the function rely on the repo being present and having all commits present.

Try switching to always update:

```typescript
await fs.access(clonePath).catch(_ => {
    console.log(`clone ${clonePath}`);
    return simpleGit().clone(currentJob.cloneUrl, clonePath, ['--depth', '10', '--branch', branchName]);
});
await simpleGit(clonePath).fetch().checkout(currentJob.pushId);
```

**Comment by gtk2k** [comment]
@steveukx 
I try it.

**Comment by gtk2k** [comment]
Thanks to that, I can clone with SHA.
