### ISSUE TITLE
Git clone with username and pwd does not set config params 

### ISSUE THREAD

**Issue by gpradeepjain** [steveukx/git-js#859]
I am doing 

```
await this.git.clone(RepoUrl, repoPath)
RepoUrl has username and pwd passed along and is an HTTPS URL. 

```
This step works, but doing rebase complains that 

`First, rewinding head to replay your work on top of it...\n\n*** Please tell me who you are.\n\nRun\n\n git config --global user.email \"you@example.com\"\n git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.`

Should I explicitly set the config by using addConfig.

**Comment by steveukx** [comment]
Hi, the username / password in the `RepoUrl` relate to how you sign in to the remote repo (for example, you might use a personal access token for Github in the repo url).

`git` asks that you have a config setting for `user.name` and `user.email` in order to commit / push, without those configuration settings `git` can't add author information to the commits.

In order to continue, you will need to use `addConfig` or use the [environment variables](https://github.com/steveukx/git-js#environment-variables) to set `GIT_AUTHOR_NAME` and `GIT_AUTHOR_EMAIL`:


```typescript
import { simpleGit } from 'simple-git';

simpleGit()
  .env({ GIT_AUTHOR_NAME: 'Your Name Here', GIT_AUTHOR_EMAIL: 'git@your-domain.dev' })
  .clone(RepoUrl, repoPath);
```
