### ISSUE TITLE
how to add permissions to create directory 

### ISSUE THREAD

**Issue by Meetverma** [steveukx/git-js#989]
upon running 
`await simpleGit().clone(url,"/deploy"+id);`
Getting en error

`GitError: fatal: could not create leading directories of '/deploy/5cUBJ': Read-only file system`

how to give access to Simple git for making a directory and writing in it? 
Thanks

**Comment by steveukx** [comment]
Hello, in order to look into this for you please include the code you are using, and the output from having enabled the verbose logging

https://github.com/steveukx/git-js/blob/main/docs/DEBUG-LOGGING-GUIDE.md

Depending on your host system, you may want to look into [chmod](https://linux.die.net/man/1/chmod) and associated nodejs docs for [fs.chown](https://nodejs.org/docs/latest/api/fs.html#filehandlechownuid-gid)
